# Generated by Django 5.1.1 on 2024-10-02 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('something', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.poll')),
            ],
        ),
    ]
