# Generated by Django 5.1.1 on 2024-10-03 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_othermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othermodel',
            name='something',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.poll'),
        ),
    ]
